### ISSUE TITLE
JSON.parse error 

### ISSUE THREAD

**Issue by rpardee** [gaeulbyul/RedBlock#10]
THANK YOU FOR REDBLOCK!

Running RedBlock add-in on firefox v79.0 94-bit, running on Win10.

Adding a session for e.g., https://twitter.com/KimmySchaal/followers

Click 'Run Chainblock' and very shortly thereafter get the following notification:

![image](https://user-images.githubusercontent.com/26327/90059693-72f4b180-dc98-11ea-9c5e-fa103fc7f2c1.png)

> Error occured.:
> SyntaxError: JASON.parse: unexpected end of data at line 1 column 1 of the JSON data

I'm guessing they changed an API on you?

**Comment by rpardee** [comment]
Seeing this on 2 different machines (though same versions of FF & windows).

**Comment by rpardee** [comment]
Similar error w/the chrome extension:
![image](https://user-images.githubusercontent.com/26327/90081197-8e27e700-dcc1-11ea-890d-7ede06d4203b.png)

**Comment by sioban** [comment]
Same problem here.

**Comment by wsxy162** [comment]
Tested on Firefox 79.0 with Linux, same error.

**Comment by gaeulbyul** [comment]
Hello,
Twitter discontinued `block_all` API which used in Red Block. I'll update my extension but sadly [it will has limitation that prevent blocking over 500 users](https://github.com/gaeulbyul/RedBlock#%EC%A3%BC%EC%9D%98). 😢

**Comment by rpardee** [comment]
😭
