### ISSUE TITLE
Suggestion: block tagged users

### ISSUE THREAD

**Issue by anonuhme** [gaeulbyul/RedBlock#11]
Feature request: It would be nice if there was an option to block users who are mentioned / tagged in a post. (Rather than likes or RTs). 

Thank you for making this plugin! <3

**Comment by gaeulbyul** [comment]
Thanks for the suggestion! Sounds good, I'll consider to implement it.

**Comment by anonuhme** [comment]
Thank you for considering it!  It would be SO helpful, especially since BlockTogether.org closed. There's currently no easy way to share large blocklists. You basically have to make a post with users names to be blocked, but this is inconvenient because we need to click on each user's @, and then block manually. Having a "block tagged users in the post" feature would be a lifesaver. Thank you so much for your time!

**Comment by gaeulbyul** [comment]
Hello, I released v0.13.0.0 with this feature!
