### ISSUE TITLE
Blocking from list doesn't work on Chrome

### ISSUE THREAD

**Issue by brosoyos** [gaeulbyul/RedBlock#14]
Importing block.js works normally in the Firefox add-on, but doing the same in the Chrome extension gives an error message "Error occurred.: ReferenceError t1 is not defined" when run and does nothing.

**Comment by gaeulbyul** [comment]
Thanks for reporting a bug! Could you provide that block.js file to me? I want to test it on my PC to investigate this issue.
(my E-mail address is: ‘aeiou256@gmail.com’)

**Comment by gaeulbyul** [comment]
Oh, never mind. I just found the cause of bug. I'll fix it in next update.
