### ISSUE TITLE
Red Block Extension broken?

### ISSUE THREAD

**Issue by Equallady** [gaeulbyul/RedBlock#19]
Today, I tried clicking on the Red Block extension and it came up blank. What went wrong?
<img width="960" alt="RedBlockerror" src="https://user-images.githubusercontent.com/87252599/125181283-6858da00-e1d1-11eb-9a26-d05843ad4a7d.png">

**Comment by gaeulbyul** [comment]
I'm terribly sorry.😭 I'll update the fixed version as soon as possible.

**Comment by Equallady** [comment]
> I'm terribly sorry.😭 I'll update the fixed version as soon as possible.

Thank you very much.
