### ISSUE TITLE
The Red Block extension goes blank when I tap on the buttons on it.

### ISSUE THREAD

**Issue by Equallady** [gaeulbyul/RedBlock#22]
<img width="960" alt="RedBlockerror2" src="https://user-images.githubusercontent.com/87252599/129651579-6dc4c029-db7e-472c-94d2-433884db5c6b.png">

**Comment by gaeulbyul** [comment]
![image](https://user-images.githubusercontent.com/830515/129718095-83bd0526-9bff-4509-8eb7-d477361c2310.png)

Hello, I'd like to check an error message to investigate what's wrong with Red Block. Could you try the following steps?

1. visit "chrome://extensions"
2. turn "Developer mode" to on.
3. open Twitter and click the Red Block button.
4. back to the extensions page, click the "Errors" button if exists.

Are there any error messages are logged?

**Comment by Equallady** [comment]
Never mind, Red Block is back and no there were no Errors today. Thank you for fixing the issue now. 

![image](https://user-images.githubusercontent.com/87252599/129793273-75f5f551-b352-4d7e-82e7-66fd62afe19e.png)
