### ISSUE TITLE
RedBlock-ChainBlock Is Not Working For Some Reason

### ISSUE THREAD

**Issue by Equallady** [gaeulbyul/RedBlock#27]
I tried using RedBlock on this particular Tweet to Block everyone who Liked, ReTweeted, and Quote-ReTweeted it, but it won't Block anyone whenever I try. 

https://twitter.com/7renkin_ps/status/1448483873717833735

**Comment by gaeulbyul** [comment]
Hello, I tried with my account but it works normally. Would you check if there's someone on retweeted(or liked) user list with your account? If that is empty, Red Block may also fail to find users to block.
(Note that retweeted/liked user list may empty if you're already blocked all of them)

**Comment by Equallady** [comment]
I kept trying to rerun RedBlock for the people I failed to chain-Block for some reason but it still won't Block those people.  It can only Block the latest people who Liked/ReTweeted/QRTed the Tweet but not the earlier ones, I don't know why.

I have an issue chain-Blocking the people on this link as well: https://twitter.com/7renkin_ps/status/1449208483799199746

![image](https://user-images.githubusercontent.com/87252599/138580121-bb9999f5-d612-4d6f-b82a-6a6d9864289d.png)
