### ISSUE TITLE
Request for adding browser plugin links to README

### ISSUE THREAD

**Issue by TheReluctantHeroes** [gaeulbyul/RedBlock#3]
Hi,

Thanks for the efforts you made at providing a better chain blocking solution. I noticed that you have built workable browser plugins for both Firefox and Chrome which has been described at https://github.com/satsukitv/twitter-block-chain/issues/66

> Firefox: https://addons.mozilla.org/en-US/firefox/addon/red-block/
> Chrome/Chromium: https://chrome.google.com/webstore/detail/red-block/knjpopecjigkkaddmoahjcfpbgedkibf

As I've tested on Chrome's side and it works well, I would highly recommend that you adding these two links to README of this repository asap. Even when English translation is not completed yet and visitors probably couldn't read Korean, as long as visitors see addons/webstore links they know instantly what to do.

**Comment by gaeulbyul** [comment]
I updated README. Thanks to notify about it!
