### ISSUE TITLE
When I try to Chain-Block using the extension:

### ISSUE THREAD

**Issue by Equallady** [gaeulbyul/RedBlock#38]
![image](https://user-images.githubusercontent.com/87252599/187091444-ce4304fa-2050-40de-8f5b-c6cbc9aa0c73.png)

When I tried to Chain-Block someone's Tweet today, it produced a blank screen instead. Why is that?

**Comment by leonoctem** [comment]
same thing happened to me over the last few days. There's also no option for redblock when I right click a tweet like there usually is. All my settings have disappeared, (one click block word list for example) and when i click on options check boxes in the extension, even in a new window, it does the same whited out thing.

**Comment by Equallady** [comment]
> same thing happened to me over the last few days. There's also no option for redblock when I right click a tweet like there usually is. All my settings have disappeared, (one click block word list for example) and when i click on options check boxes in the extension, even in a new window, it does the same whited out thing.

I'm really sorry to hear that. I have a lot of people I want to Chain-Block and this really ticks me off.

**Comment by gaeulbyul** [comment]
Hello, Could you check if there's some error messages on console? You can open the console via right-click menu on popup.

**Comment by Equallady** [comment]
> 

Alright I'll try.

**Comment by Equallady** [comment]
> Hello, Could you check if there's some error messages on console? You can open the console via right-click menu on popup.

![image](https://user-images.githubusercontent.com/87252599/188289897-63a28190-ce58-4a0d-b97a-61d2f4ff9b80.png)
