### ISSUE TITLE
What I do?

### ISSUE THREAD

**Issue by Equallady** [gaeulbyul/RedBlock#39]
My topic was closed without an answer to this question, so I don't know what to do from here. 

![image](https://user-images.githubusercontent.com/87252599/188319596-87ccefe1-d02c-46f6-9264-4e8c46eb5765.png)

**Comment by gaeulbyul** [comment]
I publish the fixed version into extension store, and awaiting review. It'll be updated automatically when it get approved.

**Comment by Equallady** [comment]
>I publish the fixed version into extension store, and awaiting review. It'll be updated automatically when it get approved.

Alright, thank you. I'll be waiting until it updates.
