### ISSUE TITLE
Blocking over 100K

### ISSUE THREAD

**Issue by serhatkar** [gaeulbyul/RedBlock#5]
Please consider allowing up to 16 million blocks. I really need it. Thanks.

**Comment by ghost** [comment]
I haven't tried yet but you may be able to block over 100K with changing the 
"MAX_USER_LIMIT" in "common.ts" file.
EDIT: I've just tried it and it works properly. You can use a source code downloader for the exact unpacked file of the extension.

**Comment by catzs** [comment]
@nsuki91 how did you download the unpacked file of the extension?
