### ISSUE TITLE
No longer works, gives a JSON-related error

### ISSUE THREAD

**Issue by Rhodanum** [gaeulbyul/RedBlock#8]
The extension no longer works on either Chrome or Firefox. Attempting to block results only in an error message and no accounts are blocked. 

In Mozilla Firefox, the error message is: Syntax Error: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data.  

In Google Chrome, the message is: SyntaxError: Unexpected end of JSON input. 

The error started occurring on June 3.

**Comment by Dio141** [comment]
same thing here.

**Comment by gaeulbyul** [comment]
Hello.
Twitter shut-downed its legacy version of Twitter in June 2020. so `block_all` API (used in current Red Block) became unavailable.
I will update to fix the problem, but there will be a restriction that Red Block shouldn't block over 500 users (to avoid a force-logout problem)

**Comment by Dio141** [comment]
welp. seems like we're back to square 1 on block apps then.

**Comment by gaeulbyul** [comment]
Well, It was just a temporary error. currently Red Block works fine..
